### ISSUE TITLE
june 6 checklist

### ISSUE THREAD

**Issue by mbwatson** [mbwatson/renci-dot-org#10]
Research Content

- [ ] groups landing (pages/groups/index.js)
- [ ] individual group tempalte page (pages/groups/[slug].js)
- [ ] collabs landing (pages/collaborations/index.js)
- [ ] individual collab template page (pages/collaborations/[slug].js)
- [ ] operations teams landing (pages/teams/index.js)
- [ ] individual operations team template page (pages/teams/[slug].js)

General Content

- [ ] ...
